// ⚠️ This file is auto-generated by generate-images.js
// Do not edit this file manually.

export const images = {
  ic_alert_triangle_fill: require('./ic_alert_triangle_fill.png'),
  ic_apple_logo: require('./ic_apple_logo.png'),
  ic_arrow_left: require('./ic_arrow_left.png'),
  ic_checkbox: require('./ic_checkbox.png'),
  ic_down_arrow: require('./ic_down_arrow.png'),
  ic_google: require('./ic_google.png'),
  ic_info_fill: require('./ic_info_fill.png'),
  ic_radio: require('./ic_radio.png'),
  ic_search: require('./ic_search.png'),
  ic_unchecked: require('./ic_unchecked.png'),
  ic_unradio: require('./ic_unradio.png'),
  ic_up_arrow: require('./ic_up_arrow.png'),
  not_found: require('./not_found.png')
};

export type ImageName = keyof typeof images;
